eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
  product-service:
    endpoints:
      endpoint:
        uri: http://PRODUCT-SERVICE
  file-service:
    endpoints:
      endpoint:
        uri: http://FILE-SERVICE   